FROM apache/airflow:2.9.0

USER airflow

RUN pip install --no-cache-dir torch --index-url https://download.pytorch.org/whl/cpu && \
    pip install --no-cache-dir \
    transformers \
    joblib \
    scikit-learn \
    qdrant-client \
    FlagEmbedding \
    groq \
    mlflow \
    wandb \
    psycopg2-binary \
    apache-airflow-providers-celery