FROM apache/airflow:2.7.3

USER airflow

RUN pip install --no-cache-dir torch --index-url https://download.pytorch.org/whl/cpu && \
    pip install --no-cache-dir \
    transformers \
    joblib \
    scikit-learn \
    qdrant-client \
    FlagEmbedding \
    groq \
    mlflow \
    wandb \
    psycopg2-binary \
    apache-airflow-providers-celery

RUN pip install --no-cache-dir \
    "ragas==0.1.21" \
    "langchain-groq" \
    "langchain-community" \
    "sentence-transformers>=2.2.2" \
    "datasets>=2.14.0" \
    --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-2.7.3/constraints-3.8.txt"