_wandb:
    value:
        cli_version: 0.26.1
        e:
            5xypm11opaoh7vxkxnqy1s855c9d1d09:
                codePath: src\absa\build_dataset.py
                codePathLocal: src\absa\build_dataset.py
                cpu_count: 12
                cpu_count_logical: 16
                disk:
                    /:
                        total: "107373129728"
                        used: "6335676416"
                email: phuonganhtran262005@gmail.com
                executable: C:\Anaconda3\python.exe
                git:
                    commit: afbdd34e82d60c6d918d9809ae5b2f88bf0d35ea
                    remote: https://github.com/phngahn/sentiment-chatbot-mlops.git
                host: LAPTOP-BG291I2D
                memory:
                    total: "34009374720"
                os: Windows-11-10.0.26200-SP0
                program: d:\Code\sentiment-chatbot-mlops\src\absa\build_dataset.py
                python: CPython 3.12.3
                root: D:\Code\sentiment-chatbot-mlops
                startedAt: "2026-05-18T07:20:15.605344Z"
                writerId: 5xypm11opaoh7vxkxnqy1s855c9d1d09
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 5
                - 53
            "2":
                - 5
                - 53
            "3":
                - 2
                - 13
            "4": 3.12.3
            "5": 0.26.1
            "8":
                - 3
            "10":
                - 20
            "12": 0.26.1
            "13": windows-amd64
